default: &default
    

development:
  base_folder: '/Users/cieclarke/Downloads/podcast/'
  <<: *default

test:
  base_folder: '/Users/cieclarke/Downloads/podcast/'
  <<: *default

production:
  <<: *default